FROM python:3.12

WORKDIR /app
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY imap-server/ ./imap-server 
COPY common/ ./common

WORKDIR /app/imap-server

CMD ["python", "-u", "server.py"]