FROM python:3.12

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY common/ ./common/
COPY smtp-server/ ./smtp-server/

WORKDIR /app/smtp-server

CMD ["python","-u","server.py"]